#Build phase
FROM node:16-alpine
WORKDIR /usr/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

# Run phase
FROM node:16-alpine
WORKDIR /usr/app
COPY package.json ./
RUN npm install
COPY --from=builder /usr/app/dist .
CMD ["npm", "start"]